"""create calculation tables

Revision ID: 9c8f64a81798
Revises:
Create Date: 2026-05-03 05:58:17.330066

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c8f64a81798"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation_inputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("s", sa.Float(), nullable=False),
        sa.Column("k", sa.Float(), nullable=False),
        sa.Column("t", sa.Float(), nullable=False),
        sa.Column("r", sa.Float(), nullable=False),
        sa.Column("sigma", sa.Float(), nullable=False),
        sa.Column("vol_shock_min", sa.Float(), nullable=False),
        sa.Column("vol_shock_max", sa.Float(), nullable=False),
        sa.Column("spot_shock_min", sa.Float(), nullable=False),
        sa.Column("spot_shock_max", sa.Float(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("cols", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calculation_outputs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calculation_id", sa.String(length=36), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("col_index", sa.Integer(), nullable=False),
        sa.Column("sigma_value", sa.Float(), nullable=False),
        sa.Column("spot_value", sa.Float(), nullable=False),
        sa.Column("call_value", sa.Float(), nullable=False),
        sa.Column("put_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["calculation_id"], ["calculation_inputs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_calculation_outputs_calculation_id",
        "calculation_outputs",
        ["calculation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_calculation_outputs_calculation_id", table_name="calculation_outputs")
    op.drop_table("calculation_outputs")
    op.drop_table("calculation_inputs")
    # ### end Alembic commands ###
